FORMAT: 1A
HOST: https://tox-ticketprint.herokuapp.com/

# TicketPrint

TicketPrint is a simple API allowing consumers to trigger print jobs of tickets.


## Tickets [/api/ticket/{id}]

+ Parameters
    + id (required, string, `ABC-123`) ... AlphaNumeric `id` of the Ticket to perform action with. Has example value.


### Get a Ticket [GET]

+ Response 200 (application/json)

        {
            "id": "ABC-123",
            "title": "Just fix the bug with highest priority",
            "description": "the description",
            "storypoints": 23,
            "projecttitle": "the project title",
            "reporter": "John Doe",
        }


## Print Jobs [/api/print]

### Create a new Print Job [POST]

Just send a JSON object with ... to trigger a print job

+ Request (application/json)

        {
            "id": "ABC-123",
            "format": 2,
            "target": "it",
        }

+ Response 200 (application/json)
